<?php

/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do NOT edit it manually. Run `php artisan openapi:generate-server`.
 */

use App\Http\ApiV1\Modules\News\Controllers\NewsController;
use Illuminate\Support\Facades\Route;

Route::post('news/news', [NewsController::class, 'create']);
Route::get('news/news/{id}', [NewsController::class, 'get']);
